### ISSUE TITLE
Error reading diff file

### ISSUE THREAD

**Issue by jbakog** [pavankjadda/LiquibaseDemo#13]
[ERROR] Error setting up or running Liquibase:
[ERROR] liquibase.command.CommandExecutionException: java.io.FileNotFoundException: src\main\resources\db\changelog\2020-05-18T20:04:44Z_changelog.xml (The filename, directory name, or volume label syntax is incorrect)

**Comment by pavankjadda** [comment]
@jbakog I added changelog folder to .gitignore. Try to create folder `src/main/resources/db/changelog` and run the mvn liquibase:diff command

**Comment by ogomaemmanuel** [comment]
getting the same error

**Comment by ogomaemmanuel** [comment]
@jbakog I found a solution, the problem is with `maven.build.timestamp`, format, you can change this format, I did this
`<properties>
        //other properties omitted  for brevity
        <timestamp>${maven.build.timestamp}</timestamp>  
        <maven.build.timestamp.format>yyyy-MM-dd.HH.mm.ss</maven.build.timestamp.format>  
    </properties>` 
and then changed 
                   `  <diffChangeLogFile>src/main/resources/db/changelog/${maven.build.timestamp}_changelog.xml</diffChangeLogFile>` to `                    <diffChangeLogFile>src/main/resources/db/changelog/${timestamp}_changelog.xml</diffChangeLogFile>`

**Comment by pavankjadda** [comment]
@jbakog @ogomaemmanuel  I never had has this issue. Could you guys upload the error log here?

**Comment by ogomaemmanuel** [comment]
I think the problem could be the OS, it like `2020-05-18T20:04:44Z_changelog.xml` filename is not allowed on windows, I am not sure about this though, so I had to format my timestamp  like `yyyy-MM-dd.HH.mm.ss`

**Comment by ogomaemmanuel** [comment]
@pavankjadda Your work really helped me a lot, it was just that small bit that was problematic

**Comment by pavankjadda** [comment]
@ogomaemmanuel  Got it. I am using macOS, that may be the reason why I don't see it

**Comment by pavankjadda** [comment]
@jbakog  Follow @ogomaemmanuel  instructions, it should the fix issue. If it still doesn't reopen the ticket

**Comment by ogomaemmanuel** [comment]
@jbakog colons are not valid windows file name, the file liquibase is trying to create has colons see [stackoverflow](https://stackoverflow.com/questions/10386344/how-to-get-a-file-in-windows-with-a-colon-in-the-filename)
